module.exports = {
  "env": {
    "browser": true,
    "es2021": true,
    "node": true
  },
  "extends": [
    "next",
    "next/core-web-vitals",
    "@antfu/eslint-config-react"
  ],
  "rules": {
    "arrow-parens": "off",
    "camelcase": "error",
    "class-methods-use-this": "off",
    "comma-dangle": "off",
    "consistent-return": 2,
    "curly": ["error", "multi-or-nest"],
    "eqeqeq": "error",
    "func-names": "off",
    "global-require": "off",
    "guard-for-in": "error",
    "indent": ["error", "tab"],
    "linebreak-style": "off",
    "max-classes-per-file": "off",
    "max-len": [1, { "code": 200 }],
    "max-statements-per-line": "off",
    "new-cap": 1,
    "no-async-promise-executor": "off",
    "no-case-declarations": 1,
    "no-console": "off",
    "no-nested-ternary": "off",
    "no-new": "off",
    "no-param-reassign": 1,
    "no-plusplus": "off",
    "no-prototype-builtins": 1,
    "no-restricted-syntax": "off",
    "no-return-await": "off",
    "no-script-url": 1,
    "no-shadow": 1,
    "no-tabs": "off",
    "no-useless-constructor": "off",
    "no-use-before-define": "off",
    "no-underscore-dangle": "off",
    "no-unused-expressions": ["error", { "allowShortCircuit": true }],
    "prefer-destructuring": 1,
    "prefer-regex-literals": "off",
    "quotes": "off",
    "quote-props": "off",
    "semi": ["error", "never", {
      "beforeStatementContinuationChars": "always"
    }],
    "antfu/top-level-function": "off",

    "import/no-unresolved": "off",
    "import/extensions": "off",
    "import/prefer-default-export": "off",
    "jsx-a11y/label-has-associated-control": "off",
    "jsx-a11y/anchor-is-valid": "off",
    "jsx-a11y/click-events-have-key-events": "off",
    "jsx-a11y/no-static-element-interactions": "off",
    "jsx-a11y/no-noninteractive-element-interactions": "off",

    "n/prefer-global/process": "off",

    "react/react-in-jsx-scope": "off",
    "react/jsx-indent": "off",
    "react/jsx-indent-props": [2, "tab"],
    "react/jsx-filename-extension": "off",
    "react/jsx-props-no-spreading": "off",
    "react/jsx-no-target-blank": "off",
    "react/display-name": "off",
    "react/prop-types": "off",
    "react/destructuring-assignment": 1,
    "react/no-array-index-key": 1,
    "react-hooks/exhaustive-deps": "error",
    "unicorn/prefer-node-protocol": "off",

    "@typescript-eslint/consistent-type-definitions": "off",
    "@typescript-eslint/indent": "off",
    "@typescript-eslint/quotes": ["error", "double"],
    "@typescript-eslint/comma-dangle": ["error", "only-multiline"],
    "@typescript-eslint/no-var-requires": "off",
    "@typescript-eslint/ban-types": 1,
    "@typescript-eslint/no-empty-function": 1,
    "@typescript-eslint/no-empty-interface": "off",
    "@typescript-eslint/explicit-module-boundary-types": "off",
    "@typescript-eslint/no-unused-vars": 1,
    "@typescript-eslint/no-explicit-any": 1,
    "@typescript-eslint/no-this-alias": 1,
    "@next/next/no-img-element": "off"
  }
}
